-- Generated by CSharp.lua Compiler
return function (dir)
  dir = (dir and #dir > 0) and (dir .. '.') or ""
  local require = require
  local load = function(module) return require(dir .. module) end

  load("Sample.TestCoroutine")
  load("Sample.TestHangingScript")
  load("Sample.TestHelloWord")

  System.init({
    "Sample.TestCoroutine",
    "Sample.TestHangingScript",
    "Sample.TestHelloWord"
  })
end
