-- Generated by CSharp.lua Compiler 1.1.0
local System = System
local UnityEngine = UnityEngine
System.namespace("", function (namespace) 
  namespace.class("TestHelloWord", function (namespace) 
    local Awake
    Awake = function (this) 
      UnityEngine.Debug.Log("hello, word")
    end
    return {
      __inherits__ = function (global) 
        return {
          global.UnityEngine.MonoBehaviour
        }
      end
    }
  end)
end)
