-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "Protocol.AutoGen.CommonPrototype",
      "Protocol.IProtocol",
      "Sample.TestCoroutine",
      "Sample.TestHangingScript",
      "Sample.TestHelloWord",
      "Sample.TestProtobuf"
    },
    types = {
      "ProtoBuf.IProtocol",
      "CSharpLua.Project.Protocol.SettingProto",
      "CSharpLua.Project.Protocol.SettingProto.ValuePairProto",
      "Sample.TestCoroutine",
      "Sample.TestHangingScript",
      "Sample.TestHelloWord",
      "Sample.TestProtobuf"
    }
  })
end
