//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_CameraClearFlagsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.CameraClearFlags));
		L.RegConstant("Skybox", UnityEngine.CameraClearFlags.Skybox);
		L.RegConstant("Color", UnityEngine.CameraClearFlags.Color);
		L.RegConstant("SolidColor", UnityEngine.CameraClearFlags.SolidColor);
		L.RegConstant("Depth", UnityEngine.CameraClearFlags.Depth);
		L.RegConstant("Nothing", UnityEngine.CameraClearFlags.Nothing);
		L.EndEnum();
		TypeTraits<UnityEngine.CameraClearFlags>.Check = CheckType;
		StackTraits<UnityEngine.CameraClearFlags>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.CameraClearFlags arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.CameraClearFlags), L, pos);
	}
}

