//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_BlendWeightsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.BlendWeights));
		L.RegConstant("OneBone", UnityEngine.BlendWeights.OneBone);
		L.RegConstant("TwoBones", UnityEngine.BlendWeights.TwoBones);
		L.RegConstant("FourBones", UnityEngine.BlendWeights.FourBones);
		L.EndEnum();
		TypeTraits<UnityEngine.BlendWeights>.Check = CheckType;
		StackTraits<UnityEngine.BlendWeights>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.BlendWeights arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.BlendWeights), L, pos);
	}
}

