//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UtilsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Utils");
		L.RegVar("MonoBehaviourInstance", get_MonoBehaviourInstance, null);
		L.RegFunction("getMonoBehaviourInstance", get_MonoBehaviourInstance);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MonoBehaviourInstance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Utils.MonoBehaviourInstance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

