//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

internal class Generic_ComponentExternionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ComponentExternions");
		L.RegFunction("GetComponent0T", GetComponent0T);
		L.RegFunction("GetComponentInChildren0T", GetComponentInChildren0T);
		L.RegFunction("GetComponentInChildren1T", GetComponentInChildren1T);
		L.RegFunction("GetComponentsInChildren0T", GetComponentsInChildren0T);
		L.RegFunction("GetComponentsInChildren2T", GetComponentsInChildren2T);
		L.RegFunction("GetComponentInParent0T", GetComponentInParent0T);
		L.RegFunction("GetComponentsInParent0T", GetComponentsInParent0T);
		L.RegFunction("GetComponentsInParent1T", GetComponentsInParent1T);
		L.RegFunction("GetComponents0T", GetComponents0T);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponent0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponent0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentInChildren0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponentInChildren0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentInChildren1T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
			System.Type arg2 = ToLua.CheckMonoType(L, 3);
			var o = Generic.ComponentExternions.GetComponentInChildren1T(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentsInChildren0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponentsInChildren0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentsInChildren2T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
			System.Type arg2 = ToLua.CheckMonoType(L, 3);
			var o = Generic.ComponentExternions.GetComponentsInChildren2T(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentInParent0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponentInParent0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentsInParent0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponentsInParent0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponentsInParent1T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
			System.Type arg2 = ToLua.CheckMonoType(L, 3);
			var o = Generic.ComponentExternions.GetComponentsInParent1T(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetComponents0T(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 1);
			System.Type arg1 = ToLua.CheckMonoType(L, 2);
			var o = Generic.ComponentExternions.GetComponents0T(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

