//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

internal class UnityEngine_ObjectWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Object), typeof(System.Object));
		L.RegFunction("GetInstanceID", GetInstanceID);
		L.RegFunction("GetHashCode", GetHashCode);
		L.RegFunction("Equals", Equals);
		L.RegFunction("Instantiate", Instantiate);
		L.RegFunction("Instantiate0", Instantiate0);
		L.RegFunction("Instantiate1", Instantiate1);
		L.RegFunction("Instantiate2", Instantiate2);
		L.RegFunction("Instantiate3", Instantiate3);
		L.RegFunction("Instantiate4", Instantiate4);
		L.RegFunction("Instantiate5", Instantiate5);
		L.RegFunction("Instantiate6", Instantiate6);
		L.RegFunction("Instantiate7", Instantiate7);
		L.RegFunction("Instantiate8", Instantiate8);
		L.RegFunction("Instantiate9", Instantiate9);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("Destroy0", Destroy0);
		L.RegFunction("Destroy1", Destroy1);
		L.RegFunction("DestroyImmediate", DestroyImmediate);
		L.RegFunction("DestroyImmediate0", DestroyImmediate0);
		L.RegFunction("DestroyImmediate1", DestroyImmediate1);
		L.RegFunction("FindObjectsOfType", FindObjectsOfType);
		L.RegFunction("DontDestroyOnLoad", DontDestroyOnLoad);
		L.RegFunction("FindObjectOfType", FindObjectOfType);
		L.RegFunction("ToString", ToString);
		L.RegFunction("New", _CreateUnityEngine_Object);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("name", get_name, set_name);
		L.RegFunction("getname", get_name);
		L.RegFunction("setname", set_name);
		L.RegVar("hideFlags", get_hideFlags, set_hideFlags);
		L.RegFunction("gethideFlags", get_hideFlags);
		L.RegFunction("sethideFlags", set_hideFlags);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Object(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				var obj = new UnityEngine.Object();
				ToLua.Push(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Object.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstanceID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			var obj = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
			var o = obj.GetInstanceID();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			var obj = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
			var o = obj.GetHashCode();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Equals(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			var obj = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			var o = obj != null ? obj.Equals(arg0) : arg0 == null;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<UnityEngine.Object>(L, 1))
			{
				return Instantiate0(L);
			}
			else if (count == 1 && TypeChecker.CheckTypes<UnityEngine.Object>(L, 1))
			{
				return Instantiate1(L);
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Transform>(L, 1))
			{
				return Instantiate2(L);
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Transform>(L, 1))
			{
				return Instantiate3(L);
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Vector3, UnityEngine.Quaternion>(L, 1))
			{
				return Instantiate4(L);
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Transform, bool>(L, 1))
			{
				return Instantiate5(L);
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Vector3, UnityEngine.Quaternion>(L, 1))
			{
				return Instantiate6(L);
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Transform, bool>(L, 1))
			{
				return Instantiate7(L);
			}
			else if (count == 4 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Transform>(L, 1))
			{
				return Instantiate8(L);
			}
			else if (count == 4 && TypeChecker.CheckTypes<UnityEngine.Object, UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Transform>(L, 1))
			{
				return Instantiate9(L);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Object.Instantiate");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate0(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			var o = UnityEngine.Object.Instantiate(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			var o = UnityEngine.Object.Instantiate(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate2(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.ToObject(L, 2);
			var o = UnityEngine.Object.Instantiate(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate3(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.ToObject(L, 2);
			var o = UnityEngine.Object.Instantiate(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate4(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 3);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate5(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.ToObject(L, 2);
			bool arg2 = LuaDLL.lua_toboolean(L, 3);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate6(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 3);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate7(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Transform arg1 = (UnityEngine.Transform)ToLua.ToObject(L, 2);
			bool arg2 = LuaDLL.lua_toboolean(L, 3);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate8(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 3);
			UnityEngine.Transform arg3 = (UnityEngine.Transform)ToLua.ToObject(L, 4);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2, arg3);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instantiate9(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 2);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 3);
			UnityEngine.Transform arg3 = (UnityEngine.Transform)ToLua.ToObject(L, 4);
			var o = UnityEngine.Object.Instantiate(arg0, arg1, arg2, arg3);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				return Destroy0(L);
			}
			else if (count == 2)
			{
				return Destroy1(L);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Object.Destroy");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy0(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object.Destroy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			float arg1 = (float)LuaDLL.lua_tonumber(L, 2);
			UnityEngine.Object.Destroy(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyImmediate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				return DestroyImmediate0(L);
			}
			else if (count == 2)
			{
				return DestroyImmediate1(L);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.Object.DestroyImmediate");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyImmediate0(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object.DestroyImmediate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyImmediate1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			bool arg1 = LuaDLL.lua_toboolean(L, 2);
			UnityEngine.Object.DestroyImmediate(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindObjectsOfType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Type arg0 = ToLua.CheckMonoType(L, 1);
			var o = UnityEngine.Object.FindObjectsOfType(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DontDestroyOnLoad(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
			UnityEngine.Object.DontDestroyOnLoad(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindObjectOfType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Type arg0 = ToLua.CheckMonoType(L, 1);
			var o = UnityEngine.Object.FindObjectOfType(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			var obj = (UnityEngine.Object)ToLua.CheckObject<UnityEngine.Object>(L, 1);
			var o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Object obj = (UnityEngine.Object)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hideFlags(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Object obj = (UnityEngine.Object)o;
			UnityEngine.HideFlags ret = obj.hideFlags;
			LuaDLL.lua_pushinteger(L, (int)ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hideFlags on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Object obj = (UnityEngine.Object)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hideFlags(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Object obj = (UnityEngine.Object)o;
			UnityEngine.HideFlags arg0 = (UnityEngine.HideFlags)LuaDLL.luaL_checknumber(L, 2);
			obj.hideFlags = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hideFlags on a nil value");
		}
	}
}

