//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_PlayModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.PlayMode));
		L.RegConstant("StopSameLayer", UnityEngine.PlayMode.StopSameLayer);
		L.RegConstant("StopAll", UnityEngine.PlayMode.StopAll);
		L.EndEnum();
		TypeTraits<UnityEngine.PlayMode>.Check = CheckType;
		StackTraits<UnityEngine.PlayMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.PlayMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.PlayMode), L, pos);
	}
}

